"""Comprehensive Test Suite for Milestone U-22: Observability & Standardized Error Handling."""

import json
import logging
import pytest
from httpx import AsyncClient

from app.core.observability import (
    JSONLogFormatter,
    current_request_id,
    telemetry_collector,
)
from app.main import app
from app.services.providers import (
    LLMMessage,
    get_llm_provider,
    get_stt_provider,
    get_tts_provider,
)


@pytest.mark.asyncio
async def test_health_check_enriched():
    """Verify root /health and /api/v1/observability/health return enriched status."""
    async with AsyncClient(app=app, base_url="http://test") as client:
        # Test root /health
        res = await client.get("/health")
        assert res.status_code == 200
        data = res.json()
        assert data["service"] == "ai-hos-backend"
        assert "status" in data
        assert "database" in data
        assert "ai_provider_mesh" in data
        assert "environment" in data

        # Test deep /api/v1/observability/health
        obs_res = await client.get("/api/v1/observability/health")
        assert obs_res.status_code == 200
        obs_data = obs_res.json()
        assert obs_data["service"] == "ai-hos-backend"
        assert "cache" in obs_data
        assert "timestamp" in obs_data
        assert obs_data["ai_provider_mesh"]["resilience_mesh_ready"] is True


@pytest.mark.asyncio
async def test_request_id_generation_and_propagation():
    """Verify X-Request-ID correlation header is generated or preserved across requests."""
    async with AsyncClient(app=app, base_url="http://test") as client:
        # 1. Autogenerated request ID
        res = await client.get("/health")
        assert res.status_code == 200
        req_id = res.headers.get("X-Request-ID")
        assert req_id is not None
        assert req_id.startswith("req_")
        assert "X-Response-Time" in res.headers

        # 2. Preserved client-supplied request ID
        custom_id = "trace-client-corr-9988"
        res_custom = await client.get("/health", headers={"X-Request-ID": custom_id})
        assert res_custom.status_code == 200
        assert res_custom.headers.get("X-Request-ID") == custom_id


@pytest.mark.asyncio
async def test_standardized_error_envelope_and_no_stack_trace_leak():
    """Verify 404 and 422 error envelopes contain request_id and sanitize stack traces."""
    async with AsyncClient(app=app, base_url="http://test") as client:
        custom_id = "err-trace-7744"
        # Test 404
        res = await client.get("/api/v1/non-existent-route-xyz", headers={"X-Request-ID": custom_id})
        assert res.status_code == 404
        assert res.headers.get("X-Request-ID") == custom_id
        
        data = res.json()
        assert "error" in data
        err = data["error"]
        assert err["code"] == "NOT_FOUND"
        assert err["request_id"] == custom_id
        assert "timestamp" in err
        # Ensure no raw python traceback is present in message or details
        assert "Traceback" not in str(data)
        assert "File \"" not in str(data)

        # Test 422 Validation Error
        val_res = await client.post(
            "/api/v1/auth/login",
            json={"email": "not-an-email"},  # missing password
            headers={"X-Request-ID": "val-trace-5566"},
        )
        assert val_res.status_code == 422
        val_data = val_res.json()
        assert "error" in val_data
        assert val_data["error"]["code"] == "VALIDATION_ERROR"
        assert val_data["error"]["request_id"] == "val-trace-5566"
        assert "errors" in val_data["error"]["details"]


@pytest.mark.asyncio
async def test_telemetry_metrics_endpoint_and_nfr_targets():
    """Verify /api/v1/observability/metrics returns NFR targets and latency distributions."""
    async with AsyncClient(app=app, base_url="http://test") as client:
        # Generate some activity
        await client.get("/health")
        await client.get("/api/v1/observability/health")

        res = await client.get("/api/v1/observability/metrics")
        assert res.status_code == 200
        data = res.json()

        assert "uptime_seconds" in data
        assert "http_requests" in data
        assert data["http_requests"]["total"] >= 2
        assert "2xx" in data["http_requests"]["status_counts"]

        # Latency metrics & NFR thresholds
        lat = data["latency_metrics"]
        assert "non_ai_api" in lat
        assert lat["non_ai_api"]["target_p95_ms"] == 500.0
        assert "target_met" in lat["non_ai_api"]

        assert "ai_conversational_turn" in lat
        assert lat["ai_conversational_turn"]["target_p95_ms"] == 3000.0

        # AI call telemetry
        ai_metrics = data["ai_call_metrics"]
        assert "total_ai_calls" in ai_metrics
        assert "fallback_rate_percent" in ai_metrics
        assert "token_usage" in ai_metrics


@pytest.mark.asyncio
async def test_ai_provider_telemetry_instrumentation():
    """Verify calling LLM, STT, and TTS records metrics into TelemetryCollector."""
    # 1. LLM call
    llm = get_llm_provider()
    res = await llm.generate([LLMMessage(role="user", content="Patient has exertional chest pain")])
    assert res.content is not None
    assert res.latency_ms >= 0

    # 2. STT call
    stt = get_stt_provider()
    stt_res = await stt.transcribe(b"dummy-audio-content", format="webm")
    assert stt_res.text is not None

    # 3. TTS call
    tts = get_tts_provider()
    tts_res = await tts.synthesize("Take two tablets daily.")
    assert len(tts_res.audio_data) > 0

    # 4. Check telemetry was recorded
    metrics = telemetry_collector.get_metrics()
    ai_metrics = metrics["ai_call_metrics"]
    assert ai_metrics["total_ai_calls"] >= 1
    assert "token_usage" in ai_metrics
    assert ai_metrics["token_usage"]["total_tokens"] >= 0


def test_structured_json_log_formatter():
    """Verify JSONLogFormatter outputs valid JSON with expected structured fields."""
    formatter = JSONLogFormatter()
    record = logging.LogRecord(
        name="aihos.test",
        level=logging.INFO,
        pathname="test.py",
        lineno=10,
        msg="Consultation session started",
        args=(),
        exc_info=None,
    )
    setattr(record, "path", "/api/v1/telehealth/session")
    setattr(record, "method", "POST")
    setattr(record, "status_code", 200)
    setattr(record, "latency_ms", 45.2)

    current_request_id.set("req_unit_test_999")
    formatted = formatter.format(record)

    data = json.loads(formatted)
    assert data["level"] == "INFO"
    assert data["logger"] == "aihos.test"
    assert data["message"] == "Consultation session started"
    assert data["request_id"] == "req_unit_test_999"
    assert data["path"] == "/api/v1/telehealth/session"
    assert data["method"] == "POST"
    assert data["status_code"] == 200
    assert data["latency_ms"] == 45.2
    assert "timestamp" in data
